### ISSUE TITLE
fix: remote worker is wrongly configured with client reports folder

### ISSUE THREAD

**Issue by Aituglo** [freelabz/secator#301]
Hey ! First, I wanted to thank you for your awesome job on this tool, that's very nice !

I want to use it as part of my recon workflow and I have some issues : 

### Deploy

I was able to deploy secator on my VPS to call it from my local machine. It works, but not really. With the default parameter, when I try to send a command from my local machine to my VPS, I get this error : 

![CleanShot 2024-04-15 at 12 13 24@2x](https://github.com/freelabz/secator/assets/6256306/432b694b-f7bf-4736-9d02-be9682636a0f)

I think that it's not an error related to celery because I was able to launch a command directly from my VPS to my VPS using the worker.

Maybe it's because my local machine is on MacOS and my VPS on Ubuntu, but I don't know why the VPS try to create and use the folder "/Users" which is only on mac. I also tried playing with environment variables to set the report folder to something else, but I keep getting these errors.

### A way to disable reports

I think it's not possible at this moment, but is it in your roadmap to disable to reports ? I plan to use your tool and to pipe it to my own recon database ( I use something like [https://github.com/honoki/bbrf-client](https://github.com/honoki/bbrf-client) ) and I don't want to store all the results in files in my hard drive.

Thanks for your help,
Regards,
Aituglo

**Comment by ocervell** [comment]
I'll admit we haven't tested much on MacOSX so far... 

Can you please give the output of `secator --version` ? 

By default `secator` tries to create folders in `$HOME/.secator` folder so make sure this is writable for your user. Now `$HOME` should expand automatically for all platforms, not sure why it would default to `/Users` on MacOSX instead of `/Users/<YOUR_USER>` ...

To fix it for you in the meantime, before running secator, you'll need to change the default directories where secator saves things:

```sh
export SECATOR_DATA_FOLDER=/path/to/writable/dir           # new reports directory that's writeable on your platform
export SECATOR_BIN_FOLDER=/path/to/writable/bin/folder  # if you want to install tools and run tasks locally as well, otherwise not necessary
```

and then everything should work as usual.

To answer your other question, we plan on making file exporters optional but they should remain the default for non-power users ... 

TBA is a `config.yml` file for secator that will allow to customize almost all `secator` defaults. In the meantime, you can override the default exporters with `-o txt` but unfortunately not remove them completely (we need a `-o none` option probably).

To integrate with your CouchDB, I suggest you look into [Drivers](https://docs.freelabz.com/in-depth/concepts/hooks-and-drivers#drivers) and try to develop your own for CouchDB. For now there is only one driver for MongoDB in `hooks/mongodb.py` which you can use as reference. 

If you're willing to help us you can contribute your CouchDB driver as a PR as well ;)
